### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by darcy3812** [darcy3812/Felix#1]
- [ ] Создание вторичных приемов
- [ ] Убрать блокировку создания приемов для неадекватных клиентов
- [ ] В окне приема перенести Товары и Услуги в tabcontrol
